import {DashboardCharts} from "@/components/dashboard-charts";
import {PipelineDiagram} from "@/components/PipelineDiagram";
import {RiskBadge} from "@/components/RiskBadge";
import {SecuritySignalsCard} from "@/components/ui/animated-dashboard-card";
import {getOverview} from "@/lib/api";

export async function Dashboard() {
  const overview = await getOverview();
  return <div className="mx-auto max-w-[1600px] space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-medium text-zinc-500">Security control center</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-white">LORE Overview</h1></div><div className="flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1 text-[11px] font-medium text-emerald-300"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />Protection active</div></div>
    <div className="grid gap-4 lg:grid-cols-[320px_minmax(0,1fr)]"><SecuritySignalsCard total={overview.trace_count + overview.tokenized_count + overview.blocked_count} primaryLabel="Tokenized" primaryValue={overview.tokenized_count} secondaryLabel="Blocked" secondaryValue={overview.blocked_count} /><section className="grid border border-white/10 bg-[#0d0d0d] sm:grid-cols-2"><div className="border-b border-white/10 p-5 sm:border-b-0 sm:border-r"><p className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Traces</p><p className="mt-4 text-4xl font-semibold tabular-nums text-white">{overview.trace_count}</p><p className="mt-3 text-xs text-zinc-500">Agent runs observed in the current window.</p></div><div className="p-5"><p className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Sensitive discoveries</p><p className="mt-4 text-4xl font-semibold tabular-nums text-white">{overview.sensitive_discovery_count}</p><p className="mt-3 text-xs text-zinc-500">Data matches found before model access.</p></div><div className="border-t border-white/10 p-5 sm:border-r"><p className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Guardrail status</p><p className="mt-4 text-base font-semibold text-emerald-400">Policy controls online</p><p className="mt-3 text-xs text-zinc-500">Semantic checks are active for incoming prompts.</p></div><div className="border-t border-white/10 p-5"><p className="text-xs font-medium uppercase tracking-[0.14em] text-zinc-500">Last refresh</p><p className="mt-4 text-base font-semibold text-white">Realtime telemetry</p><p className="mt-3 text-xs text-zinc-500">Counts refresh with each recorded trace.</p></div></section></div>
    <DashboardCharts />
    <PipelineDiagram />
    <section className="border border-white/10 bg-[#0d0d0d]"><div className="border-b border-white/10 p-4"><h2 className="text-base font-semibold text-white">Recent traces</h2></div><div className="divide-y divide-white/10">{overview.recent_traces.length ? overview.recent_traces.map((trace) => <a key={trace.trace_id} href={`/traces/${trace.trace_id}`} className="grid gap-3 p-4 transition hover:bg-white/[0.03] md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="font-mono text-xs text-zinc-200">{trace.trace_id}</div><div className="mt-1 text-xs text-zinc-500">{trace.event_count} events · {trace.last_event_at || "pending"}</div></div><div className="flex flex-wrap gap-2">{trace.data_categories.map((category) => <span key={category} className="border border-white/10 px-2 py-1 text-[11px] text-zinc-400">{category}</span>)}</div><RiskBadge blocked={trace.blocked} score={trace.max_risk_score} /></a>) : <div className="p-6 text-xs text-zinc-500">No telemetry yet. Run a webhook or demo protection request.</div>}</div></section>
  </div>;
}
